export const activityActions = {
  SYNC_ACTIVITY_PRESENCE: "SYNC_ACTIVITY_PRESENCE",
  NEW_MESSAGE: "NEW_MESSAGE",
  UPDATE_ANSWER: "UPDATE_ANSWER",
  VOTE: "VOTE",
  GET_ROOM_MESSAGES: "GET_ROOM_MESSAGES",
};
